# Generated by Django 4.2.4 on 2023-09-20 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18)),
                ('nome_empresa', models.CharField(max_length=100)),
                ('categoria_empresa', models.CharField(max_length=100)),
                ('quitado', models.BooleanField()),
                ('img', models.ImageField(upload_to='imagens', verbose_name='imagem')),
                ('data', models.DateField()),
                ('stand', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finecap.stand')),
            ],
        ),
    ]
