# Generated by Django 4.2.4 on 2023-08-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finecap", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stand",
            name="img",
        ),
        migrations.AddField(
            model_name="reserva",
            name="img",
            field=models.ImageField(
                default="", upload_to="imagens", verbose_name="imagem"
            ),
            preserve_default=False,
        ),
    ]
