# Generated by Django 4.2.4 on 2023-08-30 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finecap", "0002_remove_stand_img_reserva_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="stand",
            name="localização",
        ),
        migrations.AddField(
            model_name="stand",
            name="localizacao",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reserva",
            name="stand",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finecap.stand",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="categoria_empresa",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finecap.categoria",
            ),
        ),
    ]
