# Generated by Django 4.2.5 on 2023-09-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finecap', '0002_alter_reserva_stand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
