# Generated by Django 4.2.4 on 2023-08-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finecap', '0003_categoria_remove_stand_localização_stand_localizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='categoria_empresa',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
